-- liquibase formatted sql

-- changeset peter:1
-- Таблица для хранения бинарных данных
CREATE TABLE binary_content (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
file_as_array_of_bytes BYTEA,
CONSTRAINT pk_binary_content PRIMARY KEY (id)
);

-- Таблица для пользователей
CREATE TABLE app_user (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
telegram_user_id BIGINT,
first_login_date TIMESTAMP WITHOUT TIME ZONE,
first_name VARCHAR(255),
last_name VARCHAR(255),
user_name VARCHAR(255),
email VARCHAR(255),
is_active BOOLEAN,
app_user_state VARCHAR(255),
CONSTRAINT pk_app_user PRIMARY KEY (id)
);

-- Таблица для документов
CREATE TABLE app_document (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
telegram_file_id VARCHAR(255),
doc_name VARCHAR(255),
binary_content_id BIGINT UNIQUE,
mime_type VARCHAR(255),
file_size BIGINT,
CONSTRAINT pk_app_document PRIMARY KEY (id),
CONSTRAINT FK_APPDOCUMENT_ON_BINARYCONTENT FOREIGN KEY (binary_content_id) REFERENCES binary_content (id)
);

-- Таблица для фотографий
CREATE TABLE app_photo (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
telegram_file_id VARCHAR(255),
binary_content_id BIGINT UNIQUE,
file_size INT,
CONSTRAINT pk_app_photo PRIMARY KEY (id),
CONSTRAINT FK_APPPHOTO_ON_BINARYCONTENT FOREIGN KEY (binary_content_id) REFERENCES binary_content (id)
);

-- Таблица для "сырых" данных из Telegram
CREATE TABLE raw_data (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
update JSONB,
CONSTRAINT pk_raw_data PRIMARY KEY (id)
);

-- rollback DROP TABLE raw_data;
-- rollback DROP TABLE app_photo;
-- rollback DROP TABLE app_document;
-- rollback DROP TABLE app_user;
-- rollback DROP TABLE binary_content;